name: Build LaTeX document
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: documentation/report/
          root_file: doc.tex
          pre_compile: xelatex doc && bibtex doc && makeglossaries doc && xelatex doc
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: documentation/report/doc.pdf
      - name: Push to report branch
        run: |
          cd documentation/report
          mkdir deploy-path
          mv doc.pdf deploy-path/doc.pdf
          cd deploy-path
          git init
          git add .
          git commit -m "Deploy Report"
          git push --force "https://github.com/kreativwebdesign/lode" main:report > /dev/null 2>&1