name: Build LaTeX document
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: documentation/report/
          root_file: doc.tex
          pre_compile: xelatex doc && bibtex doc && makeglossaries doc && xelatex doc
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: documentation/report/doc.pdf
      - name: Deploy to separate branch 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: report
          FOLDER: documentation/report
          CLEAN: true # Automatically remove deleted files from the deploy branch