name: Build LaTeX document
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: documentation/report/
          root_file: doc.tex
          pre_compile: xelatex doc && bibtex doc && makeglossaries doc && xelatex doc
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: documentation/report/doc.pdf
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: report
          FOLDER: documentation/report
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}